_target_: model.models.combined_model.CombinedModel
context_norm: true

use_answers_only: false

relational_in_dim: 1024
relational_asymetrical: true
relational_activation_func: 'softmax'
relational_context_norm: true
relational_hierarchical: false

separate_relationals: true

scoring_in_dim: 80
scoring_hidden_dim: 128
scoring_pooling_type: 'max'

real_idxes: [0]

relational_in_dim_2: 1280
relational_asymetrical_2: true
relational_activation_func_2: 'softmax'
relational_context_norm_2: true
relational_hierarchical_2: false

transformer_name: ${transformer_name}
save_hyperparameters: true

scoring_transformer: null

limit_to_groups: false

slot_model:
  _target_: model.models.STSNv3.SlotAttentionAutoEncoder
  resolution:
    - ${img_size}
    - ${img_size}
  num_slots: 20
  hid_dim: 64
  num_iterations: 3
  ckpt_path: null
  save_hyperparameters: false
  save_slots: false
  freeze_slot_model: true

