_target_: model.models.scoring_model_wren_v1.ScoringModelWReN
context_norm: true
in_dim: 64
hidden_dim: 512
transformer_name: ${transformer_name}
slot_model:
  _target_: model.models.STSNv3.SlotAttentionAutoEncoder
  resolution:
    - ${img_size}
    - ${img_size}
  num_slots: 40
  hid_dim: 64
  num_iterations: 1
  ckpt_path: null
  save_hyperparameters: false
  save_slots: false
  freeze_slot_model: true

disc_pos_emb:
  _target_: model.models.pos_emb.DiscretePositionEmbedding
  out_dim: 16 # same as in_dim
  num_rows: 7
  num_cols: 2

wren_type: 'averaged'
save_hyperparameters: true
use_detection: false
use_captions: false
g_depth: 3 
f_depth: 2
use_caption_linear: false

num_correct: 2

# Carefully select for specific with respect to the task
# additional_metrics:
#   accuracy:
#     _target_: torchmetrics.classification.BinaryAccuracy
#     threshold: 0.5