_target_: pytorch_lightning.Trainer
max_epochs: ${max_epochs}
log_every_n_steps: ${log_every_n_steps}
# devices
# accelerator: auto
# devices: 1
# strategy:
#   _target_: pytorch_lightning.strategies.SingleDeviceStrategy
  # device: cuda
# num_sanity_val_steps: 0
max_time: 00:00:03:00
limit_val_batches: 10
limit_test_batches: 10
precision: 16-mixed
callbacks:
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: ${monitor}
    patience: ${early_stopping_patience}
    verbose: True
  - _target_: pytorch_lightning.callbacks.progress.TQDMProgressBar
    refresh_rate: 1
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${monitor}
    mode: min
    save_last: true
    dirpath: model_checkpoints/${get_slurm_job_id:}
    every_n_epochs: ${every_n_epochs}
    every_n_train_steps: ${every_n_train_steps}
