defaults:
  - data/tasks: []
  # - dataloader: default
  # - optimizer: adam
  - data/datamodule: single_module
  # - model: stsn
  - trainer: base
  - metrics: [mse, cross_entropy]
  - _self_
data:
  root: /app/data
torch:
  matmul_precision: medium # medium high
checkpoint_path: null # required in test.py
seed: 42
transformer_name: vit_large_patch32_384
# batch_size: 4
# img_size: 32
# num_workers: 8
# lr: 0.001
max_epochs: 500
monitor: val/loss
early_stopping_patience: 500
log_every_n_steps: 50
# target_loss_ratio: 0.3
every_n_epochs: 1  # to be changed
every_n_train_steps: null

